version: 2
updates:
  - package-ecosystem: "npm" # For JavaScript/Node.js projects
    directory: "/" # Location of the package.json file
    schedule:
      interval: "daily" # Can be "daily", "weekly", or "monthly"
